### ISSUE TITLE
[Request] Naming the downloaded files.

### ISSUE THREAD

**Issue by aneutron** [cecekpawon/Soundcloud-Downloader#1]
Is it possible to name the downloaded files ? I guess if the script just provides the link to download, we could just fetch it into localStorage and then work on it ?
_(Sorry I'm reaaaaly way behind HTML5 so I just know very few things, correct me if I'm wrong :smile: )_

**Comment by cecekpawon** [comment]
Actually we dont use html5 for single link sound, accept batch download (playlist). From now you can right click 128 link to download & name the file. Please update

**Comment by aneutron** [comment]
Very well. I'll try to hack it a bit when I can to make it named. Thanks for your efforts mate.
